<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="0.508" timestamp="2021-08-02T13:59:50.663620" hostname="Win7-2019MNTZRK"><testcase classname="" name="test_dir.test_offer" time="0.000"><error message="collection failure">ImportError while importing test module 'D:\python_work\ElinkbuyPyautoTest\test_dir\test_offer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\Python38\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_dir\test_offer.py:12: in &lt;module&gt;
    from page.offer_page import OfferPage
E   ImportError: cannot import name 'OfferPage' from 'page.offer_page' (D:\python_work\ElinkbuyPyautoTest\page\offer_page.py)</error></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\_pytest\main.py", line 257, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Program Files\Python38\lib\site-packages\_pytest\main.py", line 312, in _main
    config.hook.pytest_collection(session=session)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Program Files\Python38\lib\site-packages\_pytest\main.py", line 323, in pytest_collection
    session.perform_collect()
  File "C:\Program Files\Python38\lib\site-packages\_pytest\main.py", line 626, in perform_collect
    self.items.extend(self.genitems(node))
  File "C:\Program Files\Python38\lib\site-packages\_pytest\main.py", line 804, in genitems
    node.ihook.pytest_collectreport(report=rep)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Program Files\Python38\lib\site-packages\pytest_html\plugin.py", line 711, in pytest_collectreport
    self.append_failed(report)
  File "C:\Program Files\Python38\lib\site-packages\pytest_html\plugin.py", line 425, in append_failed
    self._appendrow("Error", report)
  File "C:\Program Files\Python38\lib\site-packages\pytest_html\plugin.py", line 393, in _appendrow
    result = self.TestResult(outcome, report, self.logfile, self.config)
  File "C:\Program Files\Python38\lib\site-packages\pytest_html\plugin.py", line 190, in __init__
    self.config.hook.pytest_html_results_table_row(report=report, cells=cells)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Program Files\Python38\lib\site-packages\pluggy\manager.py", line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Program Files\Python38\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\python_work\ElinkbuyPyautoTest\conftest.py", line 40, in pytest_html_results_table_row
    cells.insert(1, html.td(report.description))
AttributeError: 'CollectReport' object has no attribute 'description'</error></testcase></testsuite></testsuites>